// This file will be generated by: pnpm db:generate
// Run: supabase gen types typescript --local > packages/database/src/types.ts
// Then copy or re-export here

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      organization_members: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'member' | 'viewer';
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'member' | 'viewer';
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          role?: 'owner' | 'admin' | 'member' | 'viewer';
          created_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          slug: string;
          description: string | null;
          website_url: string | null;
          positioning: Json;
          brand_guidelines: Json;
          verified_claims: Json;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          slug: string;
          description?: string | null;
          website_url?: string | null;
          positioning?: Json;
          brand_guidelines?: Json;
          verified_claims?: Json;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          website_url?: string | null;
          positioning?: Json;
          brand_guidelines?: Json;
          verified_claims?: Json;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      audiences: {
        Row: {
          id: string;
          product_id: string;
          name: string;
          description: string | null;
          icp_attributes: Json;
          pain_points: Json;
          messaging_angles: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          name: string;
          description?: string | null;
          icp_attributes?: Json;
          pain_points?: Json;
          messaging_angles?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          name?: string;
          description?: string | null;
          icp_attributes?: Json;
          pain_points?: Json;
          messaging_angles?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      campaigns: {
        Row: {
          id: string;
          product_id: string;
          name: string;
          description: string | null;
          goal: string;
          goal_metric: string | null;
          goal_target: number | null;
          status: 'draft' | 'planned' | 'active' | 'paused' | 'completed' | 'cancelled';
          audience_id: string | null;
          channels: string[];
          start_date: string | null;
          end_date: string | null;
          budget_cents: number | null;
          ai_strategy: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          name: string;
          description?: string | null;
          goal: string;
          goal_metric?: string | null;
          goal_target?: number | null;
          status?: 'draft' | 'planned' | 'active' | 'paused' | 'completed' | 'cancelled';
          audience_id?: string | null;
          channels?: string[];
          start_date?: string | null;
          end_date?: string | null;
          budget_cents?: number | null;
          ai_strategy?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          name?: string;
          description?: string | null;
          goal?: string;
          goal_metric?: string | null;
          goal_target?: number | null;
          status?: 'draft' | 'planned' | 'active' | 'paused' | 'completed' | 'cancelled';
          audience_id?: string | null;
          channels?: string[];
          start_date?: string | null;
          end_date?: string | null;
          budget_cents?: number | null;
          ai_strategy?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      connectors: {
        Row: {
          id: string;
          organization_id: string;
          type: string;
          name: string;
          credentials: Json;
          config: Json;
          approval_required: boolean;
          auto_approve_types: string[];
          rate_limit_per_hour: number | null;
          rate_limit_per_day: number | null;
          active: boolean;
          last_used_at: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          type: string;
          name: string;
          credentials?: Json;
          config?: Json;
          approval_required?: boolean;
          auto_approve_types?: string[];
          rate_limit_per_hour?: number | null;
          rate_limit_per_day?: number | null;
          active?: boolean;
          last_used_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          type?: string;
          name?: string;
          credentials?: Json;
          config?: Json;
          approval_required?: boolean;
          auto_approve_types?: string[];
          rate_limit_per_hour?: number | null;
          rate_limit_per_day?: number | null;
          active?: boolean;
          last_used_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          campaign_id: string;
          parent_task_id: string | null;
          type: string;
          title: string;
          description: string | null;
          priority: number;
          status: string;
          status_history: Json;
          assigned_agent: string | null;
          connector_id: string | null;
          scheduled_for: string;
          started_at: string | null;
          completed_at: string | null;
          input_data: Json;
          draft_content: Json | null;
          final_content: Json | null;
          execution_result: Json | null;
          idempotency_key: string | null;
          retry_count: number;
          max_retries: number;
          error_log: Json;
          dry_run: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          parent_task_id?: string | null;
          type: string;
          title: string;
          description?: string | null;
          priority?: number;
          status?: string;
          status_history?: Json;
          assigned_agent?: string | null;
          connector_id?: string | null;
          scheduled_for?: string;
          started_at?: string | null;
          completed_at?: string | null;
          input_data?: Json;
          draft_content?: Json | null;
          final_content?: Json | null;
          execution_result?: Json | null;
          idempotency_key?: string | null;
          retry_count?: number;
          max_retries?: number;
          error_log?: Json;
          dry_run?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          parent_task_id?: string | null;
          type?: string;
          title?: string;
          description?: string | null;
          priority?: number;
          status?: string;
          status_history?: Json;
          assigned_agent?: string | null;
          connector_id?: string | null;
          scheduled_for?: string;
          started_at?: string | null;
          completed_at?: string | null;
          input_data?: Json;
          draft_content?: Json | null;
          final_content?: Json | null;
          execution_result?: Json | null;
          idempotency_key?: string | null;
          retry_count?: number;
          max_retries?: number;
          error_log?: Json;
          dry_run?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      approvals: {
        Row: {
          id: string;
          task_id: string;
          status: 'pending' | 'approved' | 'rejected' | 'auto_approved' | 'expired';
          requested_at: string;
          expires_at: string | null;
          resolved_at: string | null;
          resolved_by: string | null;
          resolution_notes: string | null;
          content_snapshot: Json | null;
          changes_requested: Json | null;
        };
        Insert: {
          id?: string;
          task_id: string;
          status?: 'pending' | 'approved' | 'rejected' | 'auto_approved' | 'expired';
          requested_at?: string;
          expires_at?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          content_snapshot?: Json | null;
          changes_requested?: Json | null;
        };
        Update: {
          id?: string;
          task_id?: string;
          status?: 'pending' | 'approved' | 'rejected' | 'auto_approved' | 'expired';
          requested_at?: string;
          expires_at?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          content_snapshot?: Json | null;
          changes_requested?: Json | null;
        };
      };
      policies: {
        Row: {
          id: string;
          organization_id: string;
          product_id: string | null;
          type: string;
          name: string;
          description: string | null;
          rule: Json;
          severity: 'warn' | 'block' | 'escalate';
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          product_id?: string | null;
          type: string;
          name: string;
          description?: string | null;
          rule: Json;
          severity?: 'warn' | 'block' | 'escalate';
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          product_id?: string | null;
          type?: string;
          name?: string;
          description?: string | null;
          rule?: Json;
          severity?: 'warn' | 'block' | 'escalate';
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          organization_id: string;
          action: string;
          actor_type: string;
          actor_id: string | null;
          resource_type: string | null;
          resource_id: string | null;
          old_values: Json | null;
          new_values: Json | null;
          metadata: Json;
          reversible: boolean;
          reversed_at: string | null;
          reversed_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          action: string;
          actor_type: string;
          actor_id?: string | null;
          resource_type?: string | null;
          resource_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          metadata?: Json;
          reversible?: boolean;
          reversed_at?: string | null;
          reversed_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          action?: string;
          actor_type?: string;
          actor_id?: string | null;
          resource_type?: string | null;
          resource_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          metadata?: Json;
          reversible?: boolean;
          reversed_at?: string | null;
          reversed_by?: string | null;
          created_at?: string;
        };
      };
      metrics: {
        Row: {
          id: string;
          organization_id: string;
          task_id: string | null;
          campaign_id: string | null;
          product_id: string | null;
          metric_name: string;
          metric_value: number;
          dimensions: Json;
          recorded_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          task_id?: string | null;
          campaign_id?: string | null;
          product_id?: string | null;
          metric_name: string;
          metric_value: number;
          dimensions?: Json;
          recorded_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          task_id?: string | null;
          campaign_id?: string | null;
          product_id?: string | null;
          metric_name?: string;
          metric_value?: number;
          dimensions?: Json;
          recorded_at?: string;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      campaign_status: 'draft' | 'planned' | 'active' | 'paused' | 'completed' | 'cancelled';
      task_status:
        | 'queued'
        | 'drafting'
        | 'drafted'
        | 'pending_approval'
        | 'approved'
        | 'executing'
        | 'completed'
        | 'failed'
        | 'cancelled'
        | 'evaluated';
      task_type:
        | 'blog_post'
        | 'landing_page'
        | 'email_single'
        | 'email_sequence'
        | 'social_post'
        | 'seo_optimization'
        | 'ad_campaign'
        | 'research'
        | 'analysis';
      approval_status: 'pending' | 'approved' | 'rejected' | 'auto_approved' | 'expired';
      policy_type:
        | 'rate_limit'
        | 'banned_phrase'
        | 'required_phrase'
        | 'claim_lock'
        | 'domain_allowlist'
        | 'suppression'
        | 'time_window'
        | 'budget_limit'
        | 'content_rule';
    };
  };
};

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
